// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npkiizlnziceavyoeoki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wa2lpemxuemljZWF2eW9lb2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODMxNjQsImV4cCI6MjA2NDg1OTE2NH0.yA9RapvZzj1WFT8box7cs6Cfb1FbU1sB2cOlVpU7ozo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);